# Generated by Django 5.2.14 on 2026-06-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tempo_preparacao', models.PositiveIntegerField()),
                ('ingredientes', models.ManyToManyField(to='receitas.ingrediente')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.utilizador')),
            ],
        ),
    ]
