# Generated by Django 6.0.3 on 2026-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("nivel", models.IntegerField()),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="competencias", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
