# Generated by Django 6.0.3 on 2026-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_competencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
    ]
