# Generated by Django 6.0.3 on 2026-04-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("ano", models.IntegerField()),
                ("github_url", models.URLField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
