# Generated by Django 6.0.3 on 2026-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("orientador", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("area", models.CharField(max_length=100)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
