# Generated by Django 6.0.3 on 2026-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteresseProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("area", models.CharField(max_length=100)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="interesses", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
