# Generated by Django 6.0.3 on 2026-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_makingof"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="tecnologia",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="unidade_curricular",
        ),
        migrations.AddField(
            model_name="makingof",
            name="decisoes_tomadas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="descricao_processo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="erros_correcao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="evidencia",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="makingof",
            name="justificacao_modelacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="uso_ia",
            field=models.TextField(blank=True),
        ),
    ]
