# Generated by Django 6.0.3 on 2026-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_makingof_descricao_remove_makingof_imagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="docentes/"),
        ),
        migrations.AddField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="makingof/"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="docente",
            name="pagina_lusofona",
            field=models.URLField(blank=True),
        ),
    ]
