# Generated by Django 6.0.3 on 2026-04-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alunos_delete_interesseprofissional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.TextField()),
                (
                    "TFCs",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos",
                        to="portfolio.tfc",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Alunos",
        ),
    ]
