# Generated by Django 6.0.3 on 2026-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_aluno_delete_alunos"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="entidade",
            field=models.CharField(default="Projecto", max_length=100),
            preserve_default=False,
        ),
    ]
