# Generated by Django 6.0.3 on 2026-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_makingof_entidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.AddField(
            model_name="tfc",
            name="autor",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs", to="portfolio.aluno"
            ),
        ),
    ]
