# Generated by Django 6.0.3 on 2026-04-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_remove_tfc_autor_tfc_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="TFCs",
        ),
    ]
