# Generated by Django 6.0.3 on 2026-04-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_remove_aluno_tfcs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfcs",
                to="portfolio.docente",
            ),
        ),
    ]
