# Generated by Django 6.0.3 on 2026-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="curso",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="tfc",
            name="resumo",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
