# Generated by Django 6.0.3 on 2026-04-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_tfc_curso_tfc_palavras_chave_tfc_resumo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tfcs_orientados",
                to="portfolio.docente",
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
