# Generated by Django 6.0.3 on 2026-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_tfc_ano_alter_tfc_area_remove_tfc_autor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="course_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="diploma_degree",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="reasons",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="assessment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="curricular_unit_code",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="group_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="institution_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="internship",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="language",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="methodology",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="nature",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="organic_unit",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="presentation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programme",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
