# Generated by Django 6.0.3 on 2026-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0021_licenciatura_course_code_licenciatura_diploma_degree_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="academic_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="docente",
            name="card_code",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="docente",
            name="ciencia_vitae",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="docente",
            name="degree",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="docente",
            name="employee_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="docente",
            name="orcid",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="docente",
            name="regimen",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
