# Generated by Django 6.0.3 on 2026-04-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_docente_academic_name_docente_card_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="alunos",
            field=models.ManyToManyField(
                blank=True, related_name="alunos", to="portfolio.aluno"
            ),
        ),
    ]
