# Generated by Django 5.2.13 on 2026-05-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_makingof_commit_hash_makingof_quantidade_iteracoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='descricao',
            field=models.TextField(help_text='Descrição do que faz, o que permite, e aspetos que gostou ou não'),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='portfolio.tipotecnologia'),
        ),
    ]
