# Generated by Django 5.2.14 on 2026-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_tipotecnologia_alter_tecnologia_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='palavras_chave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
